version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: codevtest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  python-sample:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8001:8001"

volumes:
  mongodb_data: